const PptxGenJS = require('pptxgenjs');
const fs = require('fs');
const path = require('path');

/**
 * 生成財報分析 PPT 報告
 * 
 * @param {Object} data - 財報分析數據
 * @param {string} outputPath - 輸出路徑
 */
function generateFinancialReport(data, outputPath) {
    const pres = new PptxGenJS();
    pres.layout = 'LAYOUT_16x9';

    // 顏色主題 - 專業金融風格
    const colors = {
        primary: '1B365D',      // 深藍色
        secondary: '2E86AB',    // 藍綠色
        accent: 'D9534F',       // 紅色（警示/負面）
        success: '5CB85C',      // 綠色（正面）
        warning: 'F0AD4E',      // 黃色（注意）
        light: 'F8F9FA',        // 淺灰背景
        dark: '343A40'          // 深灰文字
    };

    const { symbol, name, sector, reportDate, quarter } = data;

    // ===== 1. 封面頁 =====
    let slide1 = pres.addSlide({ background: { type: 'solid', color: colors.primary } });

    slide1.addText(`${name} (${symbol})`, {
        x: 0.5, y: 2, w: '90%', h: 1.2,
        fontSize: 48, color: 'FFFFFF', bold: true, align: 'center',
        fontFace: 'Arial'
    });

    slide1.addText('財報分析報告', {
        x: 0.5, y: 3.3, w: '90%', h: 0.8,
        fontSize: 28, color: colors.secondary, align: 'center',
        fontFace: 'Arial'
    });

    slide1.addText(`${sector} 產業 | ${quarter || '最新'} | ${reportDate}`, {
        x: 0.5, y: 4.5, w: '90%', h: 0.6,
        fontSize: 18, color: 'CCCCCC', align: 'center',
        fontFace: 'Arial'
    });

    slide1.addText('Generated by Zarvis Financial Analyzer', {
        x: 0.5, y: 6.8, w: '90%', h: 0.4,
        fontSize: 12, color: '888888', align: 'center'
    });

    // ===== 2. 公司概況 =====
    let slide2 = pres.addSlide({ background: { type: 'solid', color: colors.light } });

    slide2.addText('公司概況', {
        x: 0.5, y: 0.3, w: '90%', h: 0.6,
        fontSize: 32, color: colors.primary, bold: true,
        fontFace: 'Arial'
    });

    const companyInfo = [
        ['項目', '內容'],
        ['股票代碼', symbol],
        ['公司名稱', name],
        ['所屬產業', sector],
        ['財報季度', quarter || '最新'],
        ['分析日期', reportDate]
    ];

    slide2.addTable(companyInfo, {
        x: 0.5, y: 1.2, w: 9, h: 2.5,
        fontSize: 16,
        fontFace: 'Arial',
        border: { pt: 1, color: colors.secondary },
        fill: { color: 'FFFFFF' },
        colW: [3, 6]
    });

    // ===== 3. 財務摘要 =====
    let slide3 = pres.addSlide({ background: { type: 'solid', color: colors.light } });

    slide3.addText('財務摘要', {
        x: 0.5, y: 0.3, w: '90%', h: 0.6,
        fontSize: 32, color: colors.primary, bold: true,
        fontFace: 'Arial'
    });

    // 關鍵財務數據（示例數據，實際應從財報抓取）
    const financialSummary = [
        ['指標', '本期', '上期', 'YoY 變化'],
        ['營收 (億元)', data.revenue || 'N/A', data.revenue_prev || 'N/A', data.revenue_yoy || 'N/A'],
        ['毛利 (億元)', data.gross_profit || 'N/A', data.gross_profit_prev || 'N/A', data.gross_profit_yoy || 'N/A'],
        ['淨利 (億元)', data.net_income || 'N/A', data.net_income_prev || 'N/A', data.net_income_yoy || 'N/A'],
        ['EPS (元)', data.eps || 'N/A', data.eps_prev || 'N/A', data.eps_yoy || 'N/A']
    ];

    slide3.addTable(financialSummary, {
        x: 0.5, y: 1.2, w: 9, h: 2.5,
        fontSize: 14,
        fontFace: 'Arial',
        border: { pt: 1, color: colors.secondary },
        fill: { color: 'FFFFFF' },
        colW: [2.5, 2, 2, 2]
    });

    // ===== 4. 獲利能力分析 =====
    let slide4 = pres.addSlide({ background: { type: 'solid', color: colors.light } });

    slide4.addText('獲利能力分析', {
        x: 0.5, y: 0.3, w: '90%', h: 0.6,
        fontSize: 32, color: colors.primary, bold: true,
        fontFace: 'Arial'
    });

    const profitability = [
        ['指標', '本期', '上期', '產業平均', '評估'],
        ['ROE (%)', data.roe || 'N/A', data.roe_prev || 'N/A', data.roe_industry || 'N/A', data.roe_rating || 'N/A'],
        ['ROA (%)', data.roa || 'N/A', data.roa_prev || 'N/A', data.roa_industry || 'N/A', data.roa_rating || 'N/A'],
        ['毛利率 (%)', data.gross_margin || 'N/A', data.gross_margin_prev || 'N/A', data.gross_margin_industry || 'N/A', data.gross_margin_rating || 'N/A'],
        ['淨利率 (%)', data.net_margin || 'N/A', data.net_margin_prev || 'N/A', data.net_margin_industry || 'N/A', data.net_margin_rating || 'N/A']
    ];

    slide4.addTable(profitability, {
        x: 0.5, y: 1.2, w: 9, h: 2.5,
        fontSize: 13,
        fontFace: 'Arial',
        border: { pt: 1, color: colors.secondary },
        fill: { color: 'FFFFFF' },
        colW: [2, 1.5, 1.5, 1.5, 2]
    });

    // ===== 5. 財務健全度 =====
    let slide5 = pres.addSlide({ background: { type: 'solid', color: colors.light } });

    slide5.addText('財務健全度', {
        x: 0.5, y: 0.3, w: '90%', h: 0.6,
        fontSize: 32, color: colors.primary, bold: true,
        fontFace: 'Arial'
    });

    const financialHealth = [
        ['指標', '本期', '安全範圍', '評估'],
        ['負債比率 (%)', data.debt_ratio || 'N/A', '< 60%', data.debt_ratio_rating || 'N/A'],
        ['流動比率 (%)', data.current_ratio || 'N/A', '> 150%', data.current_ratio_rating || 'N/A'],
        ['速動比率 (%)', data.quick_ratio || 'N/A', '> 100%', data.quick_ratio_rating || 'N/A'],
        ['利息保障倍數', data.interest_coverage || 'N/A', '> 5x', data.interest_coverage_rating || 'N/A']
    ];

    slide5.addTable(financialHealth, {
        x: 0.5, y: 1.2, w: 9, h: 2.2,
        fontSize: 14,
        fontFace: 'Arial',
        border: { pt: 1, color: colors.secondary },
        fill: { color: 'FFFFFF' },
        colW: [3, 2, 2, 2]
    });

    // ===== 6. 現金流分析 =====
    let slide6 = pres.addSlide({ background: { type: 'solid', color: colors.light } });

    slide6.addText('現金流分析', {
        x: 0.5, y: 0.3, w: '90%', h: 0.6,
        fontSize: 32, color: colors.primary, bold: true,
        fontFace: 'Arial'
    });

    const cashflowData = [
        ['項目', '本期', '上期', '變化'],
        ['營業現金流 (億元)', data.operating_cf || 'N/A', data.operating_cf_prev || 'N/A', data.operating_cf_change || 'N/A'],
        ['投資現金流 (億元)', data.investing_cf || 'N/A', data.investing_cf_prev || 'N/A', data.investing_cf_change || 'N/A'],
        ['融資現金流 (億元)', data.financing_cf || 'N/A', data.financing_cf_prev || 'N/A', data.financing_cf_change || 'N/A'],
        ['自由現金流 (億元)', data.free_cf || 'N/A', data.free_cf_prev || 'N/A', data.free_cf_change || 'N/A']
    ];

    slide6.addTable(cashflowData, {
        x: 0.5, y: 1.2, w: 9, h: 2.2,
        fontSize: 14,
        fontFace: 'Arial',
        border: { pt: 1, color: colors.secondary },
        fill: { color: 'FFFFFF' },
        colW: [3, 2, 2, 2]
    });

    // ===== 7. 估值分析 =====
    let slide7 = pres.addSlide({ background: { type: 'solid', color: colors.light } });

    slide7.addText('估值分析', {
        x: 0.5, y: 0.3, w: '90%', h: 0.6,
        fontSize: 32, color: colors.primary, bold: true,
        fontFace: 'Arial'
    });

    const valuation = [
        ['指標', '目前', '5 年平均', '歷史百分位', '評估'],
        ['P/E (本益比)', data.pe || 'N/A', data.pe_avg5y || 'N/A', data.pe_percentile || 'N/A', data.pe_rating || 'N/A'],
        ['P/B (股價淨值比)', data.pb || 'N/A', data.pb_avg5y || 'N/A', data.pb_percentile || 'N/A', data.pb_rating || 'N/A'],
        ['股息殖利率 (%)', data.dividend_yield || 'N/A', data.dividend_yield_avg5y || 'N/A', 'N/A', data.dividend_rating || 'N/A'],
        ['P/FCF (股價自由現金流比)', data.pfcf || 'N/A', data.pfcf_avg5y || 'N/A', data.pfcf_percentile || 'N/A', data.pfcf_rating || 'N/A']
    ];

    slide7.addTable(valuation, {
        x: 0.5, y: 1.2, w: 9, h: 2.2,
        fontSize: 13,
        fontFace: 'Arial',
        border: { pt: 1, color: colors.secondary },
        fill: { color: 'FFFFFF' },
        colW: [3.5, 1.5, 1.5, 1.5, 1.5]
    });

    // ===== 8. 警示訊號 =====
    let slide8 = pres.addSlide({ background: { type: 'solid', color: colors.light } });

    slide8.addText('警示訊號', {
        x: 0.5, y: 0.3, w: '90%', h: 0.6,
        fontSize: 32, color: colors.primary, bold: true,
        fontFace: 'Arial'
    });

    const redFlags = data.red_flags || [];
    const yellowFlags = data.yellow_flags || [];

    let yPos = 1.3;

    if (redFlags.length > 0) {
        slide8.addText('🔴 紅燈警示', {
            x: 0.5, y: yPos, w: 9, h: 0.5,
            fontSize: 18, color: colors.accent, bold: true,
            fontFace: 'Arial'
        });
        yPos += 0.5;

        redFlags.forEach(flag => {
            slide8.addText(`• ${flag}`, {
                x: 0.7, y: yPos, w: 8.8, h: 0.4,
                fontSize: 14, color: colors.accent,
                fontFace: 'Arial'
            });
            yPos += 0.4;
        });
        yPos += 0.2;
    }

    if (yellowFlags.length > 0) {
        slide8.addText('🟡 黃燈警示', {
            x: 0.5, y: yPos, w: 9, h: 0.5,
            fontSize: 18, color: colors.warning, bold: true,
            fontFace: 'Arial'
        });
        yPos += 0.5;

        yellowFlags.forEach(flag => {
            slide8.addText(`• ${flag}`, {
                x: 0.7, y: yPos, w: 8.8, h: 0.4,
                fontSize: 14, color: colors.warning,
                fontFace: 'Arial'
            });
            yPos += 0.4;
        });
    }

    if (redFlags.length === 0 && yellowFlags.length === 0) {
        slide8.addText('✅ 無重大警示訊號', {
            x: 0.5, y: 1.3, w: 9, h: 0.6,
            fontSize: 20, color: colors.success, bold: true,
            fontFace: 'Arial', align: 'center'
        });
    }

    // ===== 9. AI 投資建議 =====
    let slide9 = pres.addSlide({ background: { type: 'solid', color: colors.primary } });

    slide9.addText('AI 投資建議', {
        x: 0.5, y: 0.5, w: '90%', h: 0.8,
        fontSize: 36, color: 'FFFFFF', bold: true, align: 'center',
        fontFace: 'Arial'
    });

    const recommendation = data.recommendation || '持有';
    const recColor = {
        '買入': colors.success,
        '加碼': colors.success,
        '持有': colors.warning,
        '減碼': colors.accent,
        '賣出': colors.accent
    }[recommendation] || 'FFFFFF';

    slide9.addText(recommendation, {
        x: 0.5, y: 2, w: '90%', h: 1.5,
        fontSize: 72, color: recColor, bold: true, align: 'center',
        fontFace: 'Arial'
    });

    slide9.addText(`綜合評分：${data.score || 'N/A'}/100`, {
        x: 0.5, y: 3.8, w: '90%', h: 0.8,
        fontSize: 28, color: 'FFFFFF', align: 'center',
        fontFace: 'Arial'
    });

    if (data.ai_analysis) {
        slide9.addText(data.ai_analysis, {
            x: 1, y: 4.8, w: 8, h: 1.5,
            fontSize: 16, color: 'DDDDDD', align: 'center',
            fontFace: 'Arial', rectRadius: 0.1,
            fill: { color: 'FFFFFF', transparency: 90 }
        });
    }

    // ===== 10. 風險提示 =====
    let slide10 = pres.addSlide({ background: { type: 'solid', color: colors.light } });

    slide10.addText('風險提示', {
        x: 0.5, y: 0.3, w: '90%', h: 0.6,
        fontSize: 32, color: colors.primary, bold: true,
        fontFace: 'Arial'
    });

    const risks = data.risks || [
        '產業競爭加劇風險',
        '原物料價格波動風險',
        '匯率波動風險',
        '總體經濟下行風險',
        '地緣政治風險'
    ];

    risks.forEach((risk, idx) => {
        slide10.addText(`${idx + 1}. ${risk}`, {
            x: 0.5, y: 1.3 + (idx * 0.7), w: 9, h: 0.6,
            fontSize: 16, color: colors.dark,
            fontFace: 'Arial',
            rectRadius: 0.1,
            fill: { color: 'FFFFFF' },
            border: { pt: 1, color: colors.warning },
            margin: 10
        });
    });

    // ===== 11. 結尾頁 =====
    let slide11 = pres.addSlide({ background: { type: 'solid', color: colors.primary } });

    slide11.addText('感謝聆聽', {
        x: 0.5, y: 2.5, w: '90%', h: 1,
        fontSize: 44, color: 'FFFFFF', bold: true, align: 'center',
        fontFace: 'Arial'
    });

    slide11.addText('Questions & Answers', {
        x: 0.5, y: 3.8, w: '90%', h: 0.8,
        fontSize: 24, color: colors.secondary, align: 'center',
        fontFace: 'Arial'
    });

    slide11.addText(`© ${new Date().getFullYear()} Zarvis Financial Analyzer | 報告生成日期：${reportDate}`, {
        x: 0.5, y: 6.5, w: '90%', h: 0.5,
        fontSize: 12, color: 'CCCCCC', align: 'center'
    });

    // 保存文件
    pres.writeFile({ fileName: outputPath })
        .then(() => {
            console.log(`✅ PPT 報告生成成功：${outputPath}`);
        })
        .catch((err) => {
            console.error('❌ 生成 PPT 時出錯:', err);
            process.exit(1);
        });
}

// 如果直接執行
if (require.main === module) {
    // 示例數據（實際應從分析模組獲取）
    const sampleData = {
        symbol: '2330',
        name: '台積電',
        sector: '半導體',
        reportDate: new Date().toLocaleDateString('zh-TW'),
        quarter: 'Q4-2025',
        
        // 財務數據（示例）
        revenue: '2,850',
        revenue_prev: '2,680',
        revenue_yoy: '+6.3%',
        gross_profit: '1,425',
        net_income: '980',
        eps: '38.5',
        
        // 獲利能力
        roe: '28.5',
        roa: '18.2',
        gross_margin: '50.0%',
        net_margin: '34.4%',
        
        // 財務健全度
        debt_ratio: '35.2%',
        current_ratio: '185%',
        quick_ratio: '150%',
        
        // 估值
        pe: '18.5',
        pb: '5.2',
        dividend_yield: '2.8%',
        
        // 警示
        red_flags: [],
        yellow_flags: ['毛利率較上季下滑 2 個百分點'],
        
        // 建議
        recommendation: '買入',
        score: 82,
        ai_analysis: '公司基本面強勁，獲利能力優於產業平均，估值合理。建議逢低佈局。',
        
        risks: [
            '全球半導體景氣循環風險',
            '地緣政治影響客戶訂單',
            '先進製程資本支出龐大',
            '人民幣匯率波動風險'
        ]
    };

    const outputPath = process.argv[2] || '../output/reports/sample_report.pptx';
    generateFinancialReport(sampleData, outputPath);
}

module.exports = { generateFinancialReport };
